CREATE TABLE [dbo].[applicant] (
    [id]                INT           IDENTITY (1, 1) NOT NULL,
    [LastName]          VARCHAR (255) NULL,
    [FirstName]         VARCHAR (255) NULL,
    [MiddleName]        VARCHAR (255) NULL,
    [Suffix]            VARCHAR (255) NULL,
    [Address1]          VARCHAR (255) NULL,
    [Address2]          VARCHAR (255) NULL,
    [Address3]          VARCHAR (255) NULL,
    [City]              VARCHAR (255) NULL,
    [StateID]           INT           NULL,
    [CountryID]         INT           NULL,
    [PostalCode]        VARCHAR (12)  NULL,
    [HomePhone]         VARCHAR (20)  NULL,
    [CellPhone]         VARCHAR (20)  NULL,
    [Email]             VARCHAR (255) NULL,
    [DOB]               DATETIME2 (7) NULL,
    [PlanID]            INT           NULL,
    [About]             TEXT          NULL,
    [Style]             VARCHAR (255) NULL,
    [Approved]          BIT           NULL,
    [InputIntoNCMA]     BIT           NULL,
    [ApprovedDate]      DATETIME2 (7) NULL,
    [SubmitDate]        DATETIME2 (7) NULL,
    [InputIntoNCMADate] DATETIME2 (7) NULL,
    [DojoName]          VARCHAR (255) NULL,
    CONSTRAINT [PK_applicant] PRIMARY KEY CLUSTERED ([id] ASC)
);

