CREATE TABLE [dbo].[inactivemember] (
    [ID]           INT           IDENTITY (1, 1) NOT NULL,
    [LastName]     VARCHAR (255) NULL,
    [FirstName]    VARCHAR (255) NULL,
    [MiddleName]   VARCHAR (255) NULL,
    [Suffix]       VARCHAR (255) NULL,
    [Address1]     VARCHAR (255) NULL,
    [Address2]     VARCHAR (255) NULL,
    [Address3]     VARCHAR (255) NULL,
    [City]         VARCHAR (255) NULL,
    [StateID]      INT           NULL,
    [CountryID]    INT           NULL,
    [PostalCode]   VARCHAR (12)  NULL,
    [HomePhone]    VARCHAR (20)  NULL,
    [CellPhone]    VARCHAR (20)  NULL,
    [Email]        VARCHAR (255) NULL,
    [DOB]          DATE          NULL,
    [PlanID]       INT           NULL,
    [DojoID]       INT           NULL,
    [MemberTypeID] INT           NULL,
    [DateJoined]   DATE          NULL,
    [DateOfRank]   DATE          NULL,
    [RankText]     VARCHAR (500) NULL,
    [Active]       INT           NOT NULL,
    [DateInactive] DATE          NULL,
    [DateLastPaid] DATE          NULL,
    [Comments]     TEXT          NULL
);

