CREATE TABLE [dbo].[member] (
    [ID]           INT           IDENTITY (1, 1) NOT NULL,
    [LastName]     VARCHAR (90)  NULL,
    [FirstName]    VARCHAR (90)  NULL,
    [MiddleName]   VARCHAR (40)  NULL,
    [Suffix]       VARCHAR (10)  NULL,
    [Address1]     VARCHAR (100) NULL,
    [Address2]     VARCHAR (100) NULL,
    [Address3]     VARCHAR (100) NULL,
    [City]         VARCHAR (90)  NULL,
    [StateID]      INT           NULL,
    [CountryID]    INT           NULL,
    [PostalCode]   VARCHAR (12)  NULL,
    [HomePhone]    VARCHAR (20)  NULL,
    [CellPhone]    VARCHAR (20)  NULL,
    [Email]        VARCHAR (125) NULL,
    [DOB]          DATE          NULL,
    [PlanID]       INT           NULL,
    [DojoID]       INT           NULL,
    [MemberTypeID] INT           NULL,
    [DateJoined]   DATE          NULL,
    [DateOfRank]   DATE          NULL,
    [RankText]     VARCHAR (100) NULL,
    [Active]       INT           NOT NULL,
    [DateInactive] DATE          NULL,
    [DateLastPaid] DATE          NULL,
    [Comments]     TEXT          NULL,
    CONSTRAINT [PK_member] PRIMARY KEY CLUSTERED ([ID] ASC)
);

